#!/bin/sh
STAGED_SVG_FILES=$(git diff --cached --name-only | grep '\.svg$' || true)
if [ -n "$STAGED_SVG_FILES" ]; then
  echo "SVG files changed, running yarn icons:convert..."
  yarn workspace @lidofinance/lido-ui icons:convert
  git add packages/lido-ui/src/icons/components/ packages/lido-ui/src/icons/index.tsx
fi

npx lint-staged
