name: 'Merge Storybook builds'
description: 'Merge Storybook builds from different branches'

inputs:
  branch_name:
    description: 'Branch name to merge'
    type: string
  release_type:
    description: 'Which release type to merge'
    required: true
    type: string
    options:
      - v4
      - branch
      - main
  target_folder:
    description: 'Target folder which would be pushed to github pages'
    required: true
    type: string
    default: release-target
  source_folder:
    description: 'Source folder of the build'
    type: string
    default: storybook-static
runs:
  using: 'composite'

  steps:
    - run: |
        git fetch origin gh-pages:gh-pages-temp || echo "gh-pages branch not found"
        git worktree add gh-pages-temp origin/gh-pages
      shell: bash

    - run: |
        mkdir -p ${{inputs.target_folder}}
        rsync -av gh-pages-temp/* ${{inputs.target_folder}}
      shell: bash

    - name: 'If we are deploying storybook for v4'
      if: inputs.release_type == 'v4'
      run: |
        rm -rf ${{inputs.target_folder}}/v4
        mkdir -p ${{inputs.target_folder}}/v4
      
        cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/v4/
      shell: bash

    - name: 'If we are deploying storybook for the branch'
      if: inputs.release_type == 'branch'
      run: |  
        rm -rf ${{inputs.target_folder}}/branch/${{ inputs.branch_name }}
        mkdir -p ${{inputs.target_folder}}/branch/${{ inputs.branch_name }}

        cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/branch/${{ inputs.branch_name }}
      shell: bash

    - name: 'If we are deploying main storybook'
      if: inputs.release_type == 'main'
      run: |
        shopt -s extglob
        cd ${{inputs.target_folder}}
        rm -rf !(CNAME|branch|v4)
        cd -  
        cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/
      shell: bash

