name: 'Merge Storybook builds'
description: 'Merge Storybook builds from different branches'

inputs:
  release_type:
    description: 'Which release type to merge' # v4, branch, main
    required: true
    type: string
  target_folder:
    description: 'Target folder for the merged builds'
    required: true
    type: string
    default: release-target
  source_folder:
    description: 'Source folder for the merged builds'
    required: true
    type: string
    default: storybook-static
runs:
  using: 'composite'

  steps:
    - run: |
        git fetch origin gh-pages:gh-pages-temp || echo "gh-pages branch not found"
        git worktree add gh-pages-temp origin/gh-pages
      shell: bash

    - run: |
        mkdir -p ${{inputs.target_folder}}
        mkdir -p ${{inputs.target_folder}}/v4
        mkdir -p ${{inputs.target_folder}}/branch
      shell: bash

    - run: |
        if [ -d gh-pages-temp ]; then
            rsync -av --exclude 'v4' --exclude 'branch' gh-pages-temp/ ${{inputs.target_folder}}/
            else
            echo "No main version found in gh-pages"
        fi
      if: inputs.release_type != 'main
      shell: bash


    - run: |
        if [ -d gh-pages-temp ]; then
            rsync -av gh-pages-temp/v4 ${{inputs.target_folder}}/v4/
            rsync -av gh-pages-temp/ ${{inputs.target_folder}}/branch/
            else
            echo "No main version found in gh-pages"
        fi
      if: inputs.release_type == 'main
      shell: bash

    - run: |
        cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/v4/
      if: inputs.release_type == 'v4'
      shell: bash

    - run: cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/branch/${{ github.ref_name }}
      if: inputs.release_type == 'branch'
      shell: bash

    - run: cp -r ${{inputs.source_folder}}/* ${{inputs.target_folder}}/
      if: inputs.release_type == 'main'
      shell: bash

