name: Deploy Storybook for the PR

on:
  pull_request:
    types: [ synchronize, opened, reopened ]

permissions:
  contents: write
  pages: write
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

#      - name: Setup Node
#        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
#        with:
#          node-version-file: .nvmrc
#          cache: 'yarn'

#      - name: Install Dependencies
#        run: yarn install --immutable
#
#      - name: Build Storybook
#        run: yarn build-storybook
      - run: |
          mkdir -p dist
          touch dist/index.html
          echo "This is a placeholder for the Storybook build." > dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          preview: true

# todo: publish comment to a PR
