name: Publish lido-ui-v4

on:
  push:
    branches:
      - lido-ui-v4
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Components
        run: yarn build

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          yarn release

      - name: Build Storybook
        run: yarn build-storybook

      - name: Merge Storybook builds
        uses: ./.github/actions/merge-storybook-builds
        with:
          release_type: v4
          target_folder: release-target

      - name: Deploy to GitHub Pages
        uses: lidofinance/github-pages-action@v1
        with:
          branch: gh-pages
          folder: release-target

