name: Publish

on:
  push:
    branches:
      - monorepo
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --immutable

      - run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          echo "provenance=true" >> ~/.npmrc
          yarn release
